version: '3.9'

services:
  terminal-fitness:
    container_name: terminal-fitness
    image: node:20-alpine
    working_dir: /app
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - ./data:/app/data
    ports:
      - '9003:5173'
    command: sh -c "npm install && npm run dev"

volumes:
  node_modules:
